# Generated by Django 4.1.1 on 2022-11-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCode', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Title', models.CharField(max_length=100)),
                ('Size', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Img1', models.ImageField(upload_to='')),
                ('Img2', models.ImageField(upload_to='')),
                ('Img3', models.ImageField(upload_to='')),
                ('Img4', models.ImageField(upload_to='')),
                ('Categoryid', models.BigIntegerField()),
            ],
        ),
    ]
