"""
Django settings for ESTORE project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
#pip install python-memcached
from pathlib import Path
import os
#from django.core.cache import caches

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vc)tm!t@e)qo#qql%=7i@lnq!tj50b&_bu$5)$6py^cs01wym2'  # mã hóa dữ liệu lưu trên cookies

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# configuration email  gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'thientri15102010@gmail.com'
EMAIL_HOST_PASSWORD = 'njmxrhoaxuqtqson'  
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False



#thientri15102010@gmail.com
#njmxrhoaxuqtqson
# myaccount.google.com/Iesssecureapps
# accounts.google.com/DisplayUnlockCaptcha
# myaccount.google.com/apppasswords
# Nhận thực 2 lớp thì mới bật được app password: 
# add app để generate password.





# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'product',
    'category',
    'paypal.standard.ipn',
]
#session trong caches:
# session luu o cache (RAM)
# SESSION_ENGINE =[
#     'django.contrib.sessions.backends.cache'
# ]
#settings for memcache
# CACHES = {
#     'default':{
#         'BACKEND' : 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION':['127.0.0.1:8000',
#         '127.0.0.1:8001'

#         ],
#         'TIMEOUT':60

#     }
# }

#python manage.py createcachetable


# CACHES = {
#     'default':{
#         'BACKEND' : 'django.core.cache.backends.filebased.FileBaseCache',
#         'LOCATION':'c:/cache.txt'
#     }
# }
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',   
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'home.middlewares.auth.auth_middleware'
  
]

ROOT_URLCONF = 'ESTORE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ESTORE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'eshop',
        'USER':'root',
        'PASSWORD':'Thientri@1510',
        'HOST':'localhost',
        'PORT':'3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

#thêm mới
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CART_SESSION_ID ='cart'
#Django paypal setting 
PAYPAL_RECEIVE_EMAIL = 'levanthem2002@gmail.com'
PAYPAL_TEST = True