# Generated by Django 4.1.1 on 2022-11-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
                ('CategoryCode', models.CharField(max_length=100)),
                ('Parentid', models.IntegerField()),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
